feat: 홈 화면 전체보기 및 전체보기 페이지 마크업
woowacourse-teams/2021-jujeol-jujeol pull request #130
Opened 2021-07-21 15:19 UTC by sunhpark42

## related #116 

### 설명
- 홈 화면 전체보기 config를 이용해 리스트 업
- Section 폴더에 Section 안에 들어가는 컴포넌트 구현 => 폴더 분리 필요할 것 같은데, 어떻게 나눠야 할 지 애매해서 리뷰 부탁드려용
- Section, List, CardList 추상화 및 홈화면에서 사용하는 Section 집합을 DrinkListSection으로 분리
- Grid 공통 컴포넌트 구현
- Header에 그라디언트 배경 추가

#### 미리보기
<div>
<img width="30%" alt="스크린샷 2021-07-22 오전 12 03 03" src="https://user-images.githubusercontent.com/67677561/126514170-31a300c6-531d-455c-9b35-b02a8896f3dd.png">
<img width="30%" alt="스크린샷 2021-07-22 오전 12 03 10" src="https://user-images.githubusercontent.com/67677561/126514189-683b47bd-72a2-423e-b904-a62179313366.png">
<img width="30%" alt="스크린샷 2021-07-22 오전 12 03 21" src="https://user-images.githubusercontent.com/67677561/126514194-74a23954-596b-4c41-92f9-9126d1dd0655.png">
</div>

![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/67677561/126514304-21334a14-3d5d-4ca7-b802-344a6c06261f.gif)

### 기타
#### 중점으로 봐줬으면 하는 점
- 디렉토리 구조
- Section, List 의 재사용성

2021-07-22 17:33 UTC, devhyun637 requested changes
역시 서니.. 빠른 PR에 느린 답변 죄송함니다 ㅠ.ㅠ
제가 아는 선에서 같이 이야기 해볼만한 것들 남겨보았습니다! 🌸🌸🌸
마크업 부분이니깐 최대한 마크업에 관련해서 많이 보았고, 아직 기능적인 부분의 react-query 부분은 자세히 들여다보지 않았습니다..! 이 부분은 다음에 기능이 완성되면 한번 더 보면서 리뷰하도록 하겠습니다 🙇‍♀️

직접 화면 실행시키고 느낀점은 👇
* Header가 MainHeader와 그냥 Header가 서로 높이가 다르게 측정되는거 같아서 더보기를 눌렀을 때 움직이는 듯한 느낌이 있숩니다. 혹쉬 의도한건가요?? (저는 Header 컴포넌트 어떻게 활용해야할지 모르겠어서 Mypage에는 `Styled component`로만 Header가 있는데 서니꺼 풀받고 적용하겠습니다)
* Header부분이 제 폰으로도 보고 맥북으로도 봤는데 좀 더 밝아도 저는 좋을거같아요! 서니의 의견 궁금합니당

2021-07-22 17:33 UTC, devhyun637 commented on frontend/src/components/Section/BannerSection.styles.ts
> +  position: relative;
여기 round가 사진에 가려서 보이지 않습니다ㅠ.ㅠ

2021-07-22 17:33 UTC, devhyun637 commented on frontend/src/components/Section/BannerSection.styles.ts
> +    top: 0;
오 접근성 짱..👍👍👍

2021-07-22 17:33 UTC, devhyun637 commented on frontend/src/components/Section/BannerSection.styles.ts
> +  }
오.. [object-fit](https://developer.mozilla.org/ko/docs/Web/CSS/object-fit) 배워갑니다

2021-07-22 17:33 UTC, devhyun637 commented on frontend/src/components/Section/CardList.tsx
> +    </ItemList>
이부분 `count + 2`가 어떤 의미인가용??

2021-07-22 17:33 UTC, devhyun637 commented on frontend/src/components/Section/DrinkListSection.tsx
> +}
요거 좋습니당 ㅎㅎ

2021-07-22 17:33 UTC, devhyun637 commented on frontend/src/pages/HomePage/config.ts
> +export type { HomePageConfig, ItemList, Banner };
이 방법대로 나도 통계자료 빼야겠다.. 굳굳

2021-07-22 17:33 UTC, devhyun637 commented on frontend/src/pages/HomePage/styles.ts
> +export {};
이 파일은 삭제합시당~ 아무것도 없네요..! 혹쉬 남겨둔 이유라도 있나영👀

2021-07-22 17:33 UTC, devhyun637 commented on frontend/src/pages/ViewAllPage/ViewAllPage.tsx
> +          </button>
이건 난 after로 만들었는데,
이 뒤로가기가 버튼이 있는 header도 하나의 컴포넌트로 만들면 좋을 것 같슴니다.
얘기해서 같이 하나 만들까용?.?

2021-07-22 17:36 UTC, devhyun637 commented on frontend/src/components/@shared/Grid/Grid.styles.ts
> +const Container = styled.ul<GridStyle>`
이부분 리뷰를 분명썻는데...???? 사라졌어요ㅠ.ㅠ

Grid는 Flex와 다르게 ul 태그가 아닌 곳에서 안쓰일 것 같아서, 컴포넌트화 한 것 좋습니다!
다만, col부분이나 row는 repeat안에 들어가게 되면 number type이지 않을까용?.?

2021-07-23 01:30 UTC, sunhpark42 commented on frontend/src/components/Card/Card.tsx
> +    >
...props를 이용하는 것도 방법일까? 하는 중입니당

2021-07-23 01:30 UTC, sunhpark42 commented on frontend/src/components/Section/BannerSection.styles.ts
> +  position: relative;
round 지운줄 알았는데 안지웠네용 이거 지울게요!

2021-07-23 01:32 UTC, sunhpark42 commented on frontend/src/components/Section/CardList.tsx
> +    </ItemList>
앞 뒤에 공백 추가를 위함입니다~ 앞에 before, after도 하나의 객체로 잡히더라구용

2021-07-23 01:32 UTC, sunhpark42 commented on frontend/src/pages/HomePage/styles.ts
> +export {};
HomePage style 이라 남겨두긴 했는데, 언젠간 다시 생길테니 지금은 삭제할게요~

2021-07-23 01:33 UTC, sunhpark42 commented on frontend/src/pages/ViewAllPage/ViewAllPage.tsx
> +          </button>
좋아여~ arrowButton 정도 만들면 될 것 같습니당

2021-07-23 01:43 UTC, sunhpark42 commented on frontend/src/components/@shared/Grid/Grid.styles.ts
> +const Container = styled.ul<GridStyle>`
개발 과정에서 문제가 있어서 string을 넣은 것 같은데, 지금 확인해보니 정상 동작하네용! col, row의 타입은 number로 수정했습니다!

2021-07-23 01:45 UTC, sunhpark42 commented on frontend/src/components/Section/CardList.tsx
> +    </ItemList>
<img width="317" alt="스크린샷 2021-07-23 오전 10 43 55" src="https://user-images.githubusercontent.com/67677561/126728622-be1b6415-d6ba-4aef-91f1-85a7ccfe49f5.png">

2021-07-23 01:53 UTC, sunhpark42 commented
* Header가 MainHeader와 그냥 Header가 서로 높이가 다르게 측정되는거 같아서 더보기를 눌렀을 때 움직이는 듯한 느낌이 있숩니다. 혹쉬 의도한건가요?? (저는 Header 컴포넌트 어떻게 활용해야할지 모르겠어서 Mypage에는 Styled component로만 Header가 있는데 서니꺼 풀받고 적용하겠습니다)
=> 오..티케 말 듣고 보니 높이가 다르네용. 10px정도 차이가 나는 것 같습니다. 같은 Header를 사용하고 있어서 높이가 같을 것이라고 예상하고 신경쓰지 않았는데 높이가 다르네요. Header 컴포넌트 자체가 높이를 가지고 있지 않아서 발생하는 문제인 것 같아서, 헤더 컴포넌트 자체에 높이를 주고 가운데 정렬을 시켰습니다. 확인 부탁드려요!


Header부분이 제 폰으로도 보고 맥북으로도 봤는데 좀 더 밝아도 저는 좋을거같아요! 서니의 의견 궁금합니당
=> 개인적으로는 밝으면 이런 느낌이라서, 어떻게 해야할 지 고민중이라 지금은 임시로 뒀습니다~ 이 부분은 같이 얘기해 보면 좋을 것 같아요.
<img width="334" alt="스크린샷 2021-07-23 오전 10 52 15" src="https://user-images.githubusercontent.com/67677561/126728998-66d7d12c-e30f-4889-bb24-f4eaeb00d247.png">

2021-07-23 04:29 UTC, devhyun637 commented
오 서니 일단 디렉토리 구조를 다시한번 봤는데, 역시나 어렵네요@
한가지 제안은 BannerSection은 하나의 폴더로 구분지어도 나쁘진않을 거 같아요.!
뭔가 Section이지만 다른 성격의 Section이라고 생각이 되어서..?

또 List와 Item도 다른 폴더로 분리해도 좋지 않을까하는 생각이 듭니다.
이게 Component에는 도메인과 상관없는 아이들만 넣고싶은데, 도메인과 떨어진 말랑말랑한 아이들을 만드는게 어렵군녀..

2021-07-23 04:56 UTC, devhyun637 approved these changes
좋습니다~ Approve 하겠습니다!

2021-07-23 04:57 UTC, merged