feat: 마이페이지 화면 마크업 구현
woowacourse-teams/2021-jujeol-jujeol pull request #137
Opened 2021-07-22 09:47 UTC by devhyun637

## relate #115 

### 설명
- 마이페이지 마크업 구현
- 하드코딩으로 직접 입력값을 넣어 둔 상태라서, 마크업 디자인이나 구조에 대해서 리뷰 받으면 실제 데이터로 바꾸겠습니다.

<img width="318" alt="스크린샷 2021-07-22 오후 6 29 29" src="https://user-images.githubusercontent.com/59258239/126618701-4f9128fb-1dad-4976-83a8-35e69229db08.png">

### 기타
- 아직 마이페이지에서 전체보기에 관련된 페이지는 없는 상태입니다.
- 함께 이야기 하고 싶은 부분
  - 통계부분을 컴포넌트로 빼고 싶은데, 어떻게 빼야 할 지 모르겠습니다. 😢
  - 네이밍 부분을 최대한 적절하게 짓고 싶었는데 컴포넌트 네이밍이 바뀌어야 할 부분에 대해서 이야기를 나누어보고 싶습니다.
  - 가로스크롤의 리스트의 아이템을 하나의 컴포넌트로 만들고 싶은데, 재활용이 있을 것 같지 않아서 일단 그대로 두었습니다.

2021-07-22 15:56 UTC, sunhpark42 requested changes
간단..?하게 리뷰해 보았습니당. 역시 티케 깔끔하네용 👍👍  코드를 보니까 몇몇개 같이 대화해야할 것 같은 부분이 있어서 리퀘스트 체인지 남겨 놓습니다. 내일 같이 얘기 해봐요!

그리고 스타일적인 부분에서
내가 마신 술 왼쪽 잘리는것과, 리뷰에서 제목과 날짜사이 간격이 너무 큰 것 같아서 확인해주시면 감사하겠씁니다~~~
![스크린샷 2021-07-23 오전 12 53 18](https://user-images.githubusercontent.com/67677561/126669939-e4677968-09f9-4c83-b9e6-1c06bb7da58d.png)
![스크린샷 2021-07-23 오전 12 53 59](https://user-images.githubusercontent.com/67677561/126669947-8c0b601e-969d-4a08-8ed7-49f605f1ab2b.png)

2021-07-22 15:56 UTC, sunhpark42 commented on frontend/src/components/@shared/Image/Image.styles.ts
> +interface ImageType extends ImgHTMLAttributes<HTMLImageElement> {
왜 이 타입을 쓰셨는지 알 수 있을까요? CSS 속성이면 React.CSSProperties를 이용하면 될 것 같은데 Img 태그가 가지고 있는 width, height 속성을 사용하는 것 같아용

2021-07-22 15:56 UTC, sunhpark42 commented on frontend/src/components/@shared/Image/Image.tsx
> +};
ImageType을 지정할 때 shape에 타입을 이미 지정해줘서 여기에서 별도로 받는 것이 없다면, Props대신 바로 ImageType을 넣어줘도 좋을 것 같습니다. { src, alt, size, shape }: \<ImageType> 처럼요.  src, alt 때문에 ImgHTMLAttributes\<HTMLImageElement>를 사용한 것 같네요. 개인적으로는 스타일타입이랑, 컴포넌트에서의 타입이 분리 되는 것이 좋을 것 같은데, 제가 Grid에서 스타일드 컴포넌트만 있어도 했던 것 처럼, 얘도 굳이 styled을 나눌 필요가 없을 것 같아서 같이 얘기해보고, 결정되는 방식으로 따르면 될 것 같아요!

2021-07-22 15:56 UTC, sunhpark42 commented on frontend/src/components/Card/PersonalReviewCard.tsx
> +        src="http://placehold.it/100x100"
오 이런식으로 넣을수 있군여 👀  굿굿

2021-07-22 15:56 UTC, sunhpark42 commented on frontend/src/components/Profile/Profile.tsx
> +const Profile = ({ src, nickname, introduction }: Props) => {
introduction 이름은 bio나 bioGraph로 작성하는 것이 추후에 API를 이용해서 정보를 받아올 때 덜 혼란스러울 것 같아요.

2021-07-22 15:56 UTC, sunhpark42 commented on frontend/src/pages/MyPage/index.tsx
> +        <button></button>
화살표인 것 같은데 \<button /> 으로 셀프 클로징 태그로 바꿔주세용~ 혹은 이 버튼 자체를 공통컴포넌트화 해서 여러번 사용해도 좋을 것 같아용

2021-07-22 15:56 UTC, sunhpark42 commented on frontend/src/styles/Flex.ts
> +interface FlexContainer {
extends React.CSSProperties 가 아니라 따로 타입지정을 일일히 해 주신 이유가 있나요?

2021-07-23 01:59 UTC, sunhpark42 commented
그새 PR 내용이 추가 되었네요. 완전 꼼꼼👍👍  카드형같은 경우는 재사용하게 될 것 같아서 리뷰 반영 안해주셔도 괜찮을 것 같습니다~

2021-07-23 03:48 UTC, devhyun637 commented on frontend/src/components/Profile/Profile.tsx
> +const Profile = ({ src, nickname, introduction }: Props) => {
수정했습니다!

2021-07-23 03:50 UTC, devhyun637 commented on frontend/src/pages/MyPage/index.tsx
> +        <button></button>
이것도 한번 공통 컴포넌트화 같이 이야기하고, 만들어보겠숩니당!
일단 셀프 클로징으로 바꾸었습니다

2021-07-23 03:53 UTC, devhyun637 commented on frontend/src/styles/Flex.ts
> +interface FlexContainer {
속성 별로 올 수 있는 값들이 숫자가 아니라 정해져있는 값이라고 생각해서 타입을 지정해주었는데, 어떤 방식이 더 나을까요..? 👀

2021-07-23 04:00 UTC, devhyun637 commented on frontend/src/components/@shared/Image/Image.styles.ts
> +interface ImageType extends ImgHTMLAttributes<HTMLImageElement> {
아래에서 대답을 찾으신 것 같군여👍
한가지 질문은 width, height, shape을 지정한 방식대로 사용하고 싶을 때도 `React.CSSProperties`를 써도 될까요?
이 질문이 애매모호해서 이따 만나는 시간에 다시한번 물어보겠숩니다

2021-07-23 04:00 UTC, devhyun637 commented on frontend/src/components/@shared/Image/Image.tsx
> +};
> 개인적으로는 스타일타입이랑, 컴포넌트에서의 타입이 분리 되는 것이 좋을 것 같은데

저도 alt, src는 굳이 스타일 파일에서 타입을 지정할 필요가 없다고 생각합니다.!! 같이 이야기해보아요

2021-07-23 04:22 UTC, devhyun637 commented
1. 내가 마신 술 옆면이 잘리는 건 다른 곳에서도 스크롤이 되야하는 부분을 자르는 거 같아서 그렇게 구현을 했는데, 패딩을 주는 게 나을까요??


2. 글씨 간격 줄였습니다!
<img width="319" alt="스크린샷 2021-07-23 오후 1 18 30" src="https://user-images.githubusercontent.com/59258239/126736951-7806a6de-f73d-4d8a-b6a3-40f7a349e44f.png">

2021-07-23 06:18 UTC, sunhpark42 approved these changes

2021-07-23 06:18 UTC, merged