Feature/mypage fe
woowacourse-teams/2021-jujeol-jujeol pull request #153
Opened 2021-07-27 00:44 UTC by devhyun637

## resolve #issue number

### 설명
<img src="https://user-images.githubusercontent.com/59258239/127076530-fae8177c-2a3b-4e48-89cd-6a47b427c63d.gif" width="50%" height="50%">

- 어제 코드리뷰 같이 했던 것을 바탕으로 기능 구현했습니다. 아직 세세한 부분이 많이 놓친 부분이 많은데, 보완해나가겠습니당
- [x] 내가 마신 술 리스트 전체보기 마크업
- [x] 내가 남긴 리뷰 리스트 전체보기 마크업
- [x] 내가 남긴 선호도 API 연동
- [x] 내가 남긴 리뷰 API 연동
- [x] 모아보기 리스트 무한 스크롤 구현
  - intersectionObserver 커스텀 훅 구현 및 observe 타겟 컴포넌트 생성

아직 구현이 안된 부분
- [ ] 내가 쓴 리뷰에서 수정하기 기능
- [ ] 내가 쓴 리뷰, 내가 마신 술 컴포넌트 이름이 `My-` prefix가 붙어서 유연하지 않음. 수정이 필요함.
- [ ] status 부분(현재 Statistics) 컴포넌트 이름 변경 및 config 만들어 적용하기
- [ ] 테스트 😢😢😢😢😢😢😢

같이 봐야 할 부분
- 마이페이지을 처음 로드할 때, 로그인 된 유저인지 확인하는 로직

### 기타
- 대체 이미지 그때 뭔가 빌드했을 때가 떠올라서👀 일단, 임시방편으로 `https://fakeimg.pl/72x72` https가 붙은거 가져왔습니다 ..ㅎㅎ

2021-07-27 01:59 UTC, sunhpark42 requested changes
리뷰를 하다보니 티케가 고생을 많이했겠구나 싶은 생각이 드네요 👍👍 마이페이지 너무 예쁩니다.. 대부분 history.push를 하는 부분이 다 인라인으로 되어있던데, 이부분 확인 한 번 해주세요~

그리고 UI에서 리뷰가 길어지면 글 정렬이 이상해 보여서 `text-align: justify;` 속성을 주는 것은 어떨까요??
![스크린샷 2021-07-27 오전 10 57 55](https://user-images.githubusercontent.com/67677561/127082916-931f9536-cedb-4336-b249-0cc1812169b9.png)

![스크린샷 2021-07-27 오전 10 57 30](https://user-images.githubusercontent.com/67677561/127082906-23e7af1a-69d4-430f-b3fe-c44023d80633.png)

2021-07-27 01:59 UTC, sunhpark42 commented on frontend/src/apis/requests.ts
> +  getPersonalReviews: <P, S>({ page, size }: { page?: P; size?: S }) => {
page, size 는 공통된 타입이라서 제네릭으로 받기 보다는 하나의 타입으로 통일 시켜주는게 간결할 것 같아요~

2021-07-27 01:59 UTC, sunhpark42 commented on frontend/src/components/@shared/ArrowButton/ArrowButton.tsx
> +      {name ?? ''}
ArrowButton에 name은 없어도 될 것 같아요. 이렇게 되면 '\<뒤로가기'를 원하는 때에 '뒤로가기\<' 처럼 나올 것 같네용.

ArrowButton을 Arrow라는 컴포넌트로 변경 한 후에, 외부에서 button으로 감싸 이용하거나,

ArrowButton에는 Arrow를 가진 버튼만 있는게 의미상 적절할 것 같습니다~

2021-07-27 01:59 UTC, sunhpark42 commented on frontend/src/components/@shared/Image/Image.ts
>  const Img = styled.img<ImageType>`
이거 너무 좋아요..

2021-07-27 01:59 UTC, sunhpark42 commented on frontend/src/components/Card/PersonalReviewCard.tsx
> +  const onMoveDrinkDetailPage = () => {
전 그냥 goDrinkDetail이라고 작성했는데 이 부분도 통일이 필요할 것 같네용👀 이벤트 핸들러에는 on- prefix로 사용하기로 했으니 이건 제가 onMove- 로 변경하겠습니다~ 혹은 다른 의견 있으면 던져주십셔~

2021-07-27 01:59 UTC, sunhpark42 commented on frontend/src/components/Preview/Preview.tsx
> +          onClick={() => history.push(path)}
인라인 함수!

2021-07-27 01:59 UTC, sunhpark42 commented on frontend/src/hooks/useIntersectionObserver.ts
> +const useIntersectionObserver = ({
오 훅 좋네용

2021-07-27 01:59 UTC, sunhpark42 commented on frontend/src/hooks/useIntersectionObserver.ts
> +  fetchNextPage: () => void;
개인적으로는 IntersecionObserver 는 어떤 callback함수도 받을 수 있으니까, fetchNextPage보다는 callback 과 같이 범용적인 이름을 이용하는 게 더 좋을 것 같아용.

2021-07-27 01:59 UTC, sunhpark42 commented on frontend/src/pages/MyDrinksPage/MyDrinkItem.tsx
> +      onClick={() => {
onClick을 외부에서 받고있는데, 이부분에선 인라인으로 history.push를 하고있네요. 한번 확인해주세요~

2021-07-27 01:59 UTC, sunhpark42 commented on frontend/src/pages/MyDrinksPage/index.tsx
> +        <ArrowButton size="0.7rem" borderWidth="2px" dir="LEFT" onClick={() => history.goBack()} />
여기도 인라인 함수!

2021-07-27 01:59 UTC, sunhpark42 commented on frontend/src/pages/MyPage/index.tsx
> +  const [totalMyDrinks, setTotalMyDrinks] = useState(0);
totalDrinks가 상태인 이유를 알 수 있을까요? 변경 될 일이 없을 것 같은데 상태로 관리하는 이유가 궁금해요~

2021-07-27 02:22 UTC, devhyun637 commented on frontend/src/hooks/useIntersectionObserver.ts
> +const useIntersectionObserver = ({
사실 공식문서에서 따왔다고 한다

2021-07-27 02:38 UTC, devhyun637 commented on frontend/src/pages/MyDrinksPage/MyDrinkItem.tsx
> +      onClick={() => {
외부에서 받는게 잘못된 거였읍니다.. props 속성 삭제했습니다. 감사합니다
+ 인라인 함수 분리하도록 하겠습니다!

2021-07-27 05:26 UTC, sunhpark42 commented on frontend/src/hooks/useIntersectionObserver.ts
> +const useIntersectionObserver = ({
공식문서 짱

2021-07-28 19:56 UTC, devhyun637 commented on frontend/src/apis/requests.ts
> +  getPersonalReviews: <P, S>({ page, size }: { page?: P; size?: S }) => {
수정했습니다!

2021-07-28 20:06 UTC, devhyun637 commented on frontend/src/components/@shared/ArrowButton/ArrowButton.tsx
> +      {name ?? ''}
예리하시군요👍👍👍
수정했습니다! https://github.com/woowacourse-teams/2021-jujeol-jujeol/pull/153/commits/8423e9419d22a9c6a48c0d7c89b5da74ce37dd31

2021-07-28 20:16 UTC, devhyun637 commented on frontend/src/components/Preview/Preview.tsx
> +          onClick={() => history.push(path)}
이부분은 굳이 메서드로 빼지 않아도 될 것 같아서 이렇게 쓴 건데, 통일성을 위해서 전부 onMove- prefix로 해서 뺐습니다.
네이밍에 관해서는 아직 확신이 없네여😢 
인라인 함수에 대해서 한줄로 간단히 쓸 수 있는 부분도 저희는 모두 메서드로 빼는 것을 원칙으로 할까요?.? https://github.com/woowacourse-teams/2021-jujeol-jujeol/pull/153/commits/3df2dc2a91930fb526ab0220f188a55231d373db

++ 이 부분은 `onMoveToPath`라는 네이밍으로 일단 뺏는데 너무 구체적이지 않은 이름이라 마음에 걸리네요ㅠ 피드백 부탁드립니당🙏

2021-07-29 03:24 UTC, devhyun637 commented on frontend/src/hooks/useIntersectionObserver.ts
> +  fetchNextPage: () => void;
오호 이 부분은 조금 더 이야기 해줄 수 있을까요? ` callback 과 같이 범용적인 이름을 이용하는 게` 좋다는 건 동의합니다. 그러나 현재 IntersecionObserver hook에서는 어떤 행위를 하는지 알 수 있어야하니깐 직관적으로 드러날 수 있는 이름을 써야하지않을까 라는 생각이 듭니다. 이에 대해서 제가 아직 이해를 덜 한것 같아서 조금 더 자세히 설명 부탁드립니다. 🙏

2021-07-29 08:28 UTC, devhyun637 commented on frontend/src/pages/MyPage/index.tsx
> +  const [totalMyDrinks, setTotalMyDrinks] = useState(0);
그러게요...? 수정했습니ㅏㄷ. https://github.com/woowacourse-teams/2021-jujeol-jujeol/pull/153/commits/cdffdad157092308926b14a16578bb14e571bbf3
내 상태관련해서 보여주는 `Status` 컴포넌트도 구현했습니다

2021-07-29 15:45 UTC, devhyun637 commented
서니@@ 리뷰준 내용은 거의 수정을 했습니다.
다만.. MyDrinksItem은 깔끔하게 빼고 싶은데, 컴포넌트만 계속 만드는 기분이라서 이것저것 시도해보다가 그냥 지금 상태로 두었습니다. 
후에 정말 필요할 때에 분리를 시도해보거나 추상화된 컴포넌트를 만들어보는 것도 나쁘지 않을듯..?

그리고 history를 통해 이동하는 이름들이 통일성 없이 장황해서 이부분에 대해서도 함께 이야기 나눠봐도 좋을 것 같습니당

페이지별 인증관련된 로직은 새로운 브랜치에서 적용하는 게 좋을 것 같아서 검색페이지가 완성되는 대로 로직 구상해서 적용해보겠습니다!
내 리뷰 모아보기에서 수정하기 기능도 현재 구현이 되어있지 않아서 삭제하였습니다!

2021-07-30 01:55 UTC, sunhpark42 commented on frontend/src/components/Preview/Preview.tsx
> +          onClick={() => history.push(path)}
전 return 부분에서는 돔과 관련된 것이 있고, 그 외의 로직은 위에서 확인 할 수 있는 것이 전체적인 흐름을 볼 때 더 편하다고 생각해요. 티케는 어떻게 생각하는지 궁금하네용.

아 그리고, 이건 저도 왜 그렇게 했는지 모르겠는데, 더보기 \<Link /> 로 감싸도 괜찮지 않을까요..? 왜 버튼으로 만들었지..

++ onMoveToPath 로 되어있는데, 해당 엘리먼트가 하는 역할은 더보기(or 해당 목록 전체보기)니 `onMoveToShowMore` 등은 어떨까요?

2021-07-30 01:56 UTC, sunhpark42 commented on frontend/src/components/@shared/ArrowButton/ArrowButton.tsx
> +      {name ?? ''}
이부분 Arrow와 ArrowShape가 하는 역할이 같으니 Grid나 Header처럼 styled component를 리턴하게끔 하는건 어떨까요?

2021-07-30 02:01 UTC, sunhpark42 commented on frontend/src/hooks/useIntersectionObserver.ts
> +  fetchNextPage: () => void;
IntersectionObserver는 무한스크롤을 위해서 사용되기도 하지만, 무한스크롤이 아닌경우에도 사용할 수 있어서 IntersectionObserver hook 도 결국에는 IntersectionObserver를 사용하기 위한 훅이라는 생각이 들었습니다. 그런데 지금보니까 훅 자체가 무한 스크롤을 위한 훅이었네요. 훅 이름을 바꿔보는 것도 좋을 것 같습니당.

2021-07-30 02:04 UTC, sunhpark42 commented on frontend/src/apis/requests.ts
> +  getPersonalReviews: <P, S>({ page, size }: { page?: P; size?: S }) => {
앗, 이건 둘 다 Number거나 string으로 고정시킬 수 있으니 외부에서 받아올 필요가 없다는 거였습니다 ㅠㅠㅠ  { page?: number; size?: number }처럼요! 이와 비슷하게 id 등도 타입을 정해야 할 것 같아요~

2021-07-30 02:34 UTC, devhyun637 commented on frontend/src/components/@shared/ArrowButton/ArrowButton.tsx
> +      {name ?? ''}
넵 ! 좋은거같아요 수정했씁니당

2021-07-30 02:38 UTC, devhyun637 commented on frontend/src/components/Preview/Preview.tsx
> +          onClick={() => history.push(path)}
오 저는 Homepage에서 인라인 함수를봐서 한줄은 그냥 인라인으로 쓴다고 생각을 했던 거 같아요! 
저도 전부 인라인 함수 안쓰고 메소드로 뺴는거 좋습니당!! 리팩토링 하면서 남은 인라인도 보이면 메소드로 빼겠습니다

++ Link 태그도 서니꺼보고 이런 곳에는 그냥 button으로 해서 이벤트로 넘기는게 맞는거라고 생각했던 거같은.. 다음 코드리뷰부터는 조금이라도 의문이 들면 바로바로 리뷰에 남겨보도록 하겠습니다. 내가 너무 적극적이지 못했네 😢

+++ 메소드명 수정했습니다! https://github.com/woowacourse-teams/2021-jujeol-jujeol/pull/153/commits/d98c2c260901261751d915090af2108758be2a39

2021-07-30 02:45 UTC, devhyun637 commented on frontend/src/hooks/useIntersectionObserver.ts
> +  fetchNextPage: () => void;
오호.. 이부분도 그냥 공식문서 가져와서 쓰다보니깐 이런 불상사가😢 `IntersectionObserver`를 무한 스크롤때 말고는 사용해본적이 없어서 진지하게 고민을 안하고 썼는데 오늘도 배워감니다 🙏👍 https://github.com/woowacourse-teams/2021-jujeol-jujeol/pull/153/commits/85941b61b303c77647073a2af6213007c2e64b8a

2021-07-30 02:48 UTC, sunhpark42 commented
확인했습니다~ 티케 리뷰를 하다보니 저도 과거에 왜이렇게 짠거지? 싶은게 맞네요 ㅎㅎ.. 리팩토링 빡세게 하는걸로ㅠㅠ 변경사항 확인했습니다! 수고하셨어용👍👍

2021-07-30 02:49 UTC, sunhpark42 approved these changes

2021-07-30 04:39 UTC, merged