feat: 상세페이지 선호도 평균 추가 및 리뷰 무한스크롤 구현
woowacourse-teams/2021-jujeol-jujeol pull request #179
Opened 2021-07-30 04:08 UTC by sunhpark42

## resolve #117, resolve #159, resolve #121, resolve #109

### 설명
- 상세페이지 선호도 평균 추가 및 리뷰 무한스크롤 구현
- 상세페이지 테스트 코드 작성
- button disabled 속성 추가 (#109)
<img width="480" alt="스크린샷 2021-07-30 오후 1 04 56" src="https://user-images.githubusercontent.com/67677561/127598585-29f09a02-cfc5-497a-8f43-befc8d9002be.png">

2021-07-30 08:25 UTC, devhyun637 requested changes
테코톡에 이렇게 테스트와 버그픽스까지.. 대단해서니
저는 내일 쉬는날 없이 테스트를 공부해서  열심히 큰 틀이라도 짜겠습니다.
테스트는 기본적인거 말고는 제가 경험이 많이 없어서 코드레벨에서 큰 리뷰를 줄 수 없어서 죄송합니다😢
다음에 제가 맡은 부분 짜면서 의문이 들거나 더 좋은 방향으로 적용할 수 있는 코드가 있다면 그때 한번 더 언급하면서 리팩토링 해보아용

리뷰기능에 대한 코멘트 중심으로 봐주시면 될 것 같아요!

++ 리뷰는 file changed 부분에 대해서만 가능한 걸까요,,?
문득, `수정사항이 없는데 수정버튼을 누르면 보내면 안되는거 아닐까?`라는 생각이들어서 리뷰를 남기려고 했는데 react-query에서 알아서 캐싱된 데이터로 요청을 보내지 않는건가? 이생각도 드네용. 
일단 네트워크 상에서는 PUT요청이 가긴 갑니다..!

2021-07-30 08:25 UTC, devhyun637 commented on frontend/src/pages/DrinksDetailPage/index.tsx
> +          <p>다른 사람들은 평균적으로 {preferenceAvg ?? '0'}점을 줬어요</p>
버그는 아니라서 다음주 리팩토링 때 기능 이어서 구현해도 좋을 것 같아요!

2021-07-30 08:25 UTC, devhyun637 commented on frontend/src/components/Review/ReviewEditForm.tsx
> +        setEditContent('');
수정하기 버튼 선택 => 수정하기 => `다시 수정하기 선택시 내용이 없음` 문제가 있습니다.! 확인부탁드려용

2021-07-30 08:25 UTC, devhyun637 commented on frontend/src/mocks/mockTestFunction.ts
> +class MockIntersectionObserver {
👍👍👍👍

2021-07-30 08:25 UTC, devhyun637 commented on frontend/src/pages/DrinksDetailPage/test.tsx
> +      return true;
오호 alert나 confirm은 이렇게 확인할 수 있네용..!! 싱기

2021-07-30 08:25 UTC, devhyun637 commented on frontend/src/pages/DrinksDetailPage/test.tsx
> +    API.getUserInfo = jest.fn().mockReturnValue({ data: { id: 0, nickname: '123', bio: '1234' } });
테스트지만 테스트도 유의미한 입력값을 넣으면 어떨까하는 저의 의견입니다하하👉👈

2021-07-30 08:25 UTC, devhyun637 commented on frontend/src/pages/DrinksDetailPage/test.tsx
> +    const preferenceInput = screen.getByRole('slider');
여기 `slider`이 무엇인지 알수있을까용...?

2021-07-30 08:25 UTC, devhyun637 commented on frontend/src/pages/DrinksDetailPage/test.tsx
> +    const editedReview = "oh, that's so delicious";
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 글로벌해졌다

2021-07-30 08:49 UTC, sunhpark42 commented on frontend/src/apis/requests.ts
> +    return request({ method: 'GET' as Method, url: `/drinks/${id}/reviews` + '?page=' + page });
아항 쿼리와 url 부분을 분리해서 보고 싶었습니다. 뒷 부분은 '?page=${page}'라고 변경해도 괜찮겠네요. optional일 때 undefined로 쿼리가 짜여지는게 싫어서 별로 선호하는 방식이 아니었는데, 그렇게도 되겠네용!

2021-07-30 08:49 UTC, sunhpark42 commented on frontend/src/components/RangeWithIcons/RangeWithIcons.tsx
> +        onMouseUp={onMouseUp}
넹 그렇습니다~

2021-07-30 08:50 UTC, sunhpark42 commented on frontend/src/components/Review/Review.styles.ts
> +  height: 13rem;
InfinityScrollPoll이 merge되기 전이었어서 그랬는데, 이제 머지가 되었으니 수정하겠습니당~

2021-07-30 08:51 UTC, sunhpark42 commented on frontend/src/components/Review/ReviewEditForm.tsx
> +        setEditContent('');
모달이 닫힌 이후에 모달에 value가 유지되는 것이 어색하다고 생각해서 추가되었습니다~

2021-07-30 08:54 UTC, sunhpark42 commented on frontend/src/pages/DrinksDetailPage/index.tsx
> +          <p>다른 사람들은 평균적으로 {preferenceAvg ?? '0'}점을 줬어요</p>
제가 생각하기로는 이용자가 많아질 수록 평균 선호도가 바로 변경되는 경우는 없을 것 같아요. 3.5에서 3.49가 되는 정도..? 그리고 개인 선호도를 입력한 후에 정보를 요청해서 평균값을 가지고 오는 식으로 해도 될 것 같습니당. 서버에 요청은 value가 변경되고 touch up 이나 mouse up일 때 요청을 보내고 있어서 요청이 많이 가는 건 걱정하지 않아도 될 것 같아요.

2021-07-30 08:55 UTC, sunhpark42 commented on frontend/src/pages/DrinksDetailPage/index.tsx
> +          <p>다른 사람들은 평균적으로 {preferenceAvg ?? '0'}점을 줬어요</p>
그럼 API가 추가로 필요 할 것 같네요. 다음 스프린트때 이야기 해봅시당

2021-07-30 08:55 UTC, sunhpark42 commented on frontend/src/components/Review/ReviewEditForm.tsx
> +        setEditContent('');
확인하겠습니다~

2021-07-30 08:57 UTC, sunhpark42 commented on frontend/src/pages/DrinksDetailPage/test.tsx
> +    API.getUserInfo = jest.fn().mockReturnValue({ data: { id: 0, nickname: '123', bio: '1234' } });
닉네임 1234로는 지정못할까요..?😂

2021-07-30 08:57 UTC, sunhpark42 commented on frontend/src/pages/DrinksDetailPage/test.tsx
> +    const preferenceInput = screen.getByRole('slider');
input range의 role이 slider 입니당~

2021-07-31 07:17 UTC, sunhpark42 commented on frontend/src/apis/requests.ts
> +    return request({ method: 'GET' as Method, url: `/drinks/${id}/reviews` + '?page=' + page });
이부분 page가 항상 required인지 조건이 없을때 default가 있게 할 것인지에 따라서 작성하는게 달라질 것 같아서 우선은 그대로 두었습니다~

2021-07-31 07:21 UTC, sunhpark42 commented
리뷰 반영해 보았습니다~

> [**@shared**](https://github.com/shared)에 있는 `InfinityScrollPoll` 컴포넌트를 수정하여 가져와도 좋을거같아요!

*   무한스크롤 공통 컴포넌트, 훅으로 변경 [c4fa619](https://github.com/woowacourse-teams/2021-jujeol-jujeol/pull/179/commits/c4fa619289df082fb4731ed790bed15f9c6f298c)

> 문득, `수정사항이 없는데 수정버튼을 누르면 보내면 안되는거 아닐까?`라는 생각이들어서 리뷰를 남기려고 했는데 react-query에서 알아서 캐싱된 데이터로 요청을 보내지 않는건가? 이생각도 드네용.

*   modal 열고 닫힌 상태에 따라서 리뷰 수정 폼의 내용을 채우고, 비우는 로직 추가 eab8051
    *   이 부분은 리팩토링을 할 때 어떻게 의존성을 제거할 수 있을지 생각해 봐야할 것 같아요 ㅠㅠ 어렵네용..
*   리뷰 수정 시 내용이 변경되지 않고 수정버튼을 누를 시 요청 보내지 않도록 수정 99e81d4

> 테스트지만 테스트도 유의미한 입력값을 넣으면 어떨까하는 저의 의견입니다하하👉👈

*   test 데이터를 명시적으로 변경 [32e2a18](https://github.com/woowacourse-teams/2021-jujeol-jujeol/pull/179/commits/32e2a188d0c5b650cca96f6421e82a69624708e2)

2021-07-31 12:38 UTC, devhyun637 commented on frontend/src/pages/DrinksDetailPage/test.tsx
> +    API.getUserInfo = jest.fn().mockReturnValue({ data: { id: 0, nickname: '123', bio: '1234' } });
아ㅋㅋㅋ그러네 이걸 보니 bio 수정 기능도 있어야겠네요 :) 다음 스프린트때 개인 프로필 수정 UI를 어떻게할지 이야기를 해봐야겠어여..! 
단순하게 닉네임만 수정할 수 있을거라고 생각해서 말한거였습니다 :)

2021-07-31 13:10 UTC, devhyun637 approved these changes
좋아용! Approve 하겠습니다!
모달과 수정의 의존성문제는 같이 좀더 고민해보아용

2021-07-31 19:51 UTC, merged