feat: 검색결과 없음 화면 구현
woowacourse-teams/2021-jujeol-jujeol pull request #277
Opened 2021-08-06 07:59 UTC by sunhpark42

## resolve #276 

### 설명
- 검색결과 없음 화면 구현
- 결과없음 안내 + 다른 주류 추천 목록 보여주기
<img width="317" alt="스크린샷 2021-08-06 오후 4 53 38" src="https://user-images.githubusercontent.com/67677561/128476801-871c99cc-541c-4769-84cc-093610d6f4f0.png">
<img width="315" alt="스크린샷 2021-08-06 오후 4 53 46" src="https://user-images.githubusercontent.com/67677561/128476899-b55e4275-756a-4269-bb39-16a7f09e9e37.png">

### 기타
- type.d.ts 의 내용을 정리했습니다. 중복되는 부분들을 제거했습니다. (commit: 245c0a9)
- Line Clamp 관련 스타일을 LineClamp 컴포넌트로 분리하였습니다. (commit : efd4dec)

2021-08-08 12:17 UTC, devhyun637 requested changes
서니 정리왕이야... 내가 저지른 일을 다 수습하고 계시는군여
검색결과 페이지에서 글자수 제한에 대한 이슈 & 글자수가 길어지면 가로 스크롤이 생기는 이슈에 대해서만 함께 이야기하고 수정하면 될 거 같습니다!

그 부분 때문에 Request Changes 할게요!
타입 정리한거 진짜 좋다

2021-08-08 12:17 UTC, devhyun637 commented on frontend/src/types.d.ts
> +  interface MyDrinkItem extends Pick<Item, 'id' | 'name' | 'imageUrl'> {
크.. 타입 정리 미쳤다. 👍👍👍
이제야 제대로 확인하는데, 서니 쵝오

++ MyDrinkItem도 PersonalDrinkItem으로 바꾸어야할지 네이밍에 대한 고민이 됩니당
나중에 다른 사람이 좋아한 술 이런거 모아보기 기능이 생길수도 있고, 일단 네이밍의 통일성을 위해서..?
이건 한번 얘기해봐도 좋을 거 같아요. 정리 왕 서니 짱짱맨

2021-08-08 12:17 UTC, devhyun637 commented on frontend/src/styles/LineClamp.ts
> +export default LineClamp;
좋아요

2021-08-08 15:59 UTC, sunhpark42 commented on frontend/src/pages/SearchResultPage/NoSearchResult.styles.ts
> +  row-gap: 2rem;
오 그것도 좋네용

2021-08-09 02:43 UTC, sunhpark42 reviewed
리뷰에 답글을 남긴줄 알았는데.. pending상태였네요.😂

2021-08-09 04:55 UTC, sunhpark42 commented
> 검색결과 페이지에서 글자수 제한에 대한 이슈 & 글자수가 길어지면 가로 스크롤이 생기는 이슈에 대해서만 함께 이야기하고 수정하면 될 거 

@devhyun637 ㅇ이게 정확히 어떤 경우인가요?? 글자수를 길게 작성해도 재현이 안돼서, 캡쳐본 포함해주시면 좋을 것 같아요~ 아님 이따 같이 봐용!

2021-08-09 04:55 UTC, sunhpark42 commented
> 검색결과 페이지에서 글자수 제한에 대한 이슈 & 글자수가 길어지면 가로 스크롤이 생기는 이슈에 대해서만 함께 이야기하고 수정하면 될 거 

@devhyun637 ㅇ이게 정확히 어떤 경우인가요?? 글자수를 길게 작성해도 재현이 안돼서, 캡쳐본 포함해주시면 좋을 것 같아요~ 아님 이따 같이 봐용!

2021-08-09 06:06 UTC, devhyun637 commented
이것입니다! 영문으로 썼을때만 그러네용..!!
<img width="315" alt="스크린샷 2021-08-06 오후 4 53 46" src="https://user-images.githubusercontent.com/59258239/128665590-0a4c11c2-98b2-4c71-a388-a420e272a8f4.gif">

2021-08-09 13:32 UTC, devhyun637 approved these changes
Approve 합니다~

2021-08-09 13:32 UTC, devhyun637 commented on frontend/src/pages/SearchResultPage/index.tsx
> +  });
오 👍👍

2021-08-09 13:32 UTC, devhyun637 commented on frontend/src/pages/SearchResultPage/index.tsx
> +    ({ pageParam = 1 }) => API.getDrinks({ params, page: pageParam }),
좋아용!! 굳이 새로운걸 만들 필요가 없구나 좋아요 중복삭제

2021-08-09 13:32 UTC, devhyun637 commented on frontend/src/pages/SearchResultPage/index.tsx
> +  } = useInfiniteQuery(
나는 왜 상태에 상태를 만들고 이상하다 여기면서 이 방법을 떠올리지 못한걸까
서니가 복지다..

2021-08-09 13:33 UTC, sunhpark42 commented on frontend/src/pages/SearchResultPage/index.tsx
> +  } = useInfiniteQuery(
원래 남이 만든 도구는 이해하기 어려운 법이졍

2021-08-09 13:34 UTC, merged