feat: 모바일에서 모달 끌어서 닫기 기능 구현
woowacourse-teams/2021-jujeol-jujeol pull request #284
Opened 2021-08-07 08:17 UTC by devhyun637

## resolve #118

### 설명
- 모달 모바일에서 끌어서 닫는 기능 구현
- 웹의 경우에는 마우스로 클릭을 해서 닫는 것을 drag 이벤트로 구현을 해야하는데, `draggble`한 속성의 element의 경우 통제가 어렵다는 점을 감안해서 웹은 기존의 dimmed된 영역을 선택해서 닫기를 구현하는 것을 유지
- 스크린 리더 상에서 tab으로 이동할 수 있는 닫기 버튼을 추가로 구현
<img width="450" alt="스크린 리더에서 보여주는 모달 닫기 버튼에 대한 사진" src="https://user-images.githubusercontent.com/59258239/128593629-0e69fc2b-c1a6-4338-8ae8-eb949764b0e4.png">

- esc 버튼을 선택한 것만으로도 모달이 닫아질 수 있도록 구현
- 스타일 : dimmed 된 영역 선택 시 모달이 부드럽게 닫힐 수 있도록 애니메이션 추가 (현재 모바일에서 끌어서 내리는 부분은 애니메이션 없이 구현되어 있는데, 특별히 어색한 부분은 없는 것 같습니다)
<img width="318" alt="모달 끌어서 닫기 시연 gif" src="https://user-images.githubusercontent.com/59258239/128593618-57d98418-2db4-45c7-adc7-bf7e2ec81540.gif">

### 기타
- 숨겨진 x 버튼과 esc 기능을 만들고나서 보니, 굳이 두개가 다있어야하나? 이 고민이 듭니당. 뭔가 스크린 리더를 사용하는 분들도 esc버튼을 선택해서 끄지 않을까하는 생각이 드는데 서니의 의견 주세용🙏
- 모달이 실제 모바일에서 보니깐 왜 80%가 되었는지 모르겠지만 꽉차는 듯한 느낌이 있는데 65~ 70%vh도 나름 괜찮아 보입니다! 확인한번 해주세용
<img width="200" alt="실제 모달이 모바일에서 보여지는 화면 캡쳐본 사진" src="https://user-images.githubusercontent.com/59258239/128593627-856435a8-2b81-4b01-8426-d2d9b08f4eb3.jpeg">

2021-08-08 16:29 UTC, sunhpark42 reviewed
진짜 티케가 구현하는 UI는 언제봐도 멋지네용. 웹과 모바일 모두 놓지지 않으려는 게 정말 멋져용

> 숨겨진 x 버튼과 esc 기능을 만들고나서 보니, 굳이 두개가 다있어야하나? 이 고민이 듭니당. 뭔가 스크린 리더를 사용하는 분들도 esc버튼을 선택해서 끄지 않을까하는 생각이 드는데 서니의 의견 주세용
- 전 둘 다 있는게 좋다고 생각합니다. 둘 다 모달을 닫는 방법이고, 어떤 방법이 더 편한지는 개인의 선택 문제라고 생각해요.

2021-08-08 16:29 UTC, sunhpark42 commented on frontend/src/components/Card/ReviewCard.tsx
> +import EditButton from '../@shared/MeatBallsButton/MeatBallsButton';
진짜 미트볼 ㅋㅋㅋㅋㅋㅋ 이게 뭐람...

2021-08-08 16:29 UTC, sunhpark42 commented on frontend/src/components/Card/ReviewCard.tsx
> +          <EditButton ariaLabel="내 리뷰 글 수정하기 버튼" onClick={onOpenEditForm} />
깔끔하네요 굿굿

2021-08-08 16:29 UTC, sunhpark42 commented on frontend/src/components/Modal/Modal.styles.ts
> +          transition: all 1s;
이 부분은 all보다는 특정해서 그 타이밍을 조절해 주는게 좋아서, transform, opacity로 하는 건 어떨까요?

2021-08-08 16:29 UTC, sunhpark42 commented on frontend/src/components/Modal/Modal.tsx
> +          X
이것도 SVG로 그려놓을까요?

2021-08-09 01:58 UTC, sunhpark42 requested changes
1. 데스크탑에서 탭으로 닫기 버튼에 포커싱이 안됩니다. (크롬) 확인 부탁드려요!
2. 지금이 65~70% 인걸까요? 전 현재 모달 크기 좋아용!
<img width="400" alt="KakaoTalk_Photo_2021-08-09-10-57-45" src="https://user-images.githubusercontent.com/67677561/128653498-a41bbec6-cbce-4a9c-961f-8429011c991b.jpeg">

<img width="400" alt="KakaoTalk_Photo_2021-08-09-10-57-40" src="https://user-images.githubusercontent.com/67677561/128653496-19a252fc-14d4-44f7-9c57-e4af4e447549.jpeg">

2021-08-09 10:07 UTC, devhyun637 commented on frontend/src/components/Card/ReviewCard.tsx
> +import EditButton from '../@shared/MeatBallsButton/MeatBallsButton';
후..누가 이름 정했어 누구야ㅠ

2021-08-09 10:08 UTC, devhyun637 commented on frontend/src/components/Modal/Modal.tsx
> +          X
아이콘 사이즈 서니가 알려주면 제가 그사이즈 맞추어서 넣을게요! (근데 stroke 그런거 잘 몰라서 비율 똥망되면 어뜩해?)!ㅜ!

2021-08-09 11:46 UTC, devhyun637 commented on frontend/src/components/Modal/Modal.styles.ts
> +          transition: all 1s;
오 거의 대부분의 속성을 `transition-property`로 넣을수가 있구나.. 수정하겠숩니당

2021-08-09 11:49 UTC, devhyun637 commented on frontend/src/components/Modal/Modal.tsx
> +          X
넵 이름을 뭐라고해서 만들까용?.?

2021-08-09 12:36 UTC, devhyun637 commented on frontend/src/components/Modal/Modal.tsx
> +          X
서니랑 얘기한 이후에, 안보이는 영역의 '닫기'버튼의 경우에는 정확한 버튼명을 명시해주었고, 탭 인덱스로 이동했을 때 사람들 눈에 보이도록 opacity 0.5정도를 주었습니다.!
<img width="335" alt="스크린샷 2021-08-09 오후 9 15 44" src="https://user-images.githubusercontent.com/59258239/128706691-f5d09208-9caf-4e02-a956-1d28931f169d.png">

2021-08-09 12:41 UTC, devhyun637 commented
서니 모달 닫기 버튼이 보이도록 수정하고, transition 적용 속성 명시해주었습니다!
또 서니 리뷰의 이미지가 엄청 커서 살짝 줄였습니다. ㅎㅅㅎ (모니터 사야지 말만 오억오조번째)

2021-08-09 12:47 UTC, sunhpark42 commented on frontend/src/components/Modal/Modal.tsx
> +          X
굿굿

2021-08-09 12:51 UTC, sunhpark42 approved these changes
확인했습니당

2021-08-09 13:40 UTC, merged