feat: 리뷰가 0개일 때의 화면 처리 및 선호도를 입력하지 않으면 리뷰를 입력할 수 없는 기능 구현
woowacourse-teams/2021-jujeol-jujeol pull request #290
Opened 2021-08-08 08:44 UTC by devhyun637

## resolve #289 #288 

### 설명
- 리뷰가 0개일 때 화면처리
- 선호도를 입력하지 않으면 (서버에서 받은 선호도가 0인 경우) 리뷰 입력폼이 선호도를 입력해야 한다는 버튼과 안내로 바뀌도록 UI 구현
- 선호도 입력하기를 선택하면 선호도 입력 폼으로 scroll 되도록 구현 (별이 3초간 깜빡거리게 구현해보았습니당)
<img width="307" alt="스크린샷 2021-08-08 오후 5 29 17" src="https://user-images.githubusercontent.com/59258239/128626319-da391b68-55ec-4847-b543-d39553e2529d.png">
<img width="320" alt="선호도 입력 gif" src="https://user-images.githubusercontent.com/59258239/128626355-76c18c1c-af18-49a2-9b90-124d579baf65.gif">

### 기타
- 생각해보니 `버튼 있으면 좋겠다`라고만 이야기하고, UI 설계를 하지 않아서 일단 제가 생각하는 최선의 UI를 만들어보았습니다. 완벽하게 맘에 드는 화면이 아니라서 피드백 받습니다아🙏 
- 현재 상세화면에서 서니가 만들어둔 `window.scrollTo`가 먹지 않아서 저도 ref를 사용해서 스크롤을 하게 만들었는데 이 이유를 찾지 못했숩니당.. 왜 안될까

2021-08-08 08:47 UTC, devhyun637 commented on frontend/src/pages/DrinksDetailPage/index.tsx
> +    setIsScrolled(true);
이부분에서 바로 state에 대한 값을 css에 적용한다고 생각해서 원래는 `prevState`를 사용했는데, 안해도 되더라구요..!?! 같은 메서드 안에서 사용하는 게 아니라서 굳이 `prevState`를 사용할 필요가 없을까요??

2021-08-08 16:23 UTC, sunhpark42 reviewed
우와 티케 진짜 잘 만들어주셨네용 멋졍!
다만 리뷰와 리뷰를 작성해달라는 카드 사이가 너무 좁아보이는 것 같아서 간격이 좀 있었으면 하는 바람입니당.
이 부분도 마찬가지로 현재 코드만 봐서, 내일 아침에 풀 받아서 확인하겠습니다.

2021-08-08 16:23 UTC, sunhpark42 commented on frontend/src/components/Review/DisableWriteReview.tsx
> +const DisableWriteReview = ({ onClick }: { onClick: MouseEventHandler<HTMLButtonElement> }) => {
onClick 이라고 되어있어서 카드 전체에 onClick이 들어간다고 이해할 수도 있을 것 같아요. 이미 도메인에 종속적으로 선호도 입력하러 가기라고 되어있으니 보다 명확한 props 이름을 사용하는건 어떨까요?

2021-08-08 16:23 UTC, sunhpark42 commented on frontend/src/components/Review/NoReviews.styles.ts
> +    span {
이 부분도 술의 이름이 길어지면 한 줄을 넘어갈 수도 있을 것 같아요~

2021-08-08 16:23 UTC, sunhpark42 commented on frontend/src/hooks/useReviews.ts
> +  useInfinityScroll({ target: observerTargetRef, fetchNextPage, hasNextPage });
리뷰 좋네용! 다만 무한 스크롤과 관련된 부분은 리뷰보다는, 기획과 연관 된 부분인 것 같아서, UseReview에서는 리뷰와 관련된 로직만 가지고 있고, fetchNextPage, hasNextPage를 return해서 밖에서 사용할 수 있도록 하는건 어떨까요??

2021-08-08 16:23 UTC, sunhpark42 commented on frontend/src/pages/DrinksDetailPage/index.tsx
> +  };
이 부분을 시간으로 제한하는건 조금 어색해 보입니다. 한 번 더 좋은 방법을 같이 생각해봐용

2021-08-08 16:23 UTC, sunhpark42 commented on frontend/src/pages/DrinksDetailPage/index.tsx
> +    setIsScrolled(true);
정확이 어떤 의미인지 이해가 잘 가지 않아서 내일 설명 부탁드려요!

2021-08-08 16:23 UTC, sunhpark42 commented on frontend/src/pages/DrinksDetailPage/index.tsx
> +  };
굳이 상태로 관리하지 않아도 될 것 같기도 합니당

2021-08-08 16:23 UTC, sunhpark42 commented on frontend/src/pages/DrinksDetailPage/styles.ts
> +const PreferenceSection = styled.section<{ isScrolled: boolean }>`
아하 상태가 애니메이션때문이었군용. 그럼 isScrolled보다는 blink에 관련된 이름이 더 좋아보여용~

2021-08-08 16:24 UTC, sunhpark42 commented on frontend/src/pages/DrinksDetailPage/styles.ts
> +const PreferenceSection = styled.section<{ isScrolled: boolean }>`
개인적으론 아예 사라지는 것보다 투명도를 낮추는 식으로 해도 될 것 같아용

2021-08-09 02:41 UTC, sunhpark42 requested changes
UI 리뷰 완료했습니다.
+) 전체적으로 line-height를 1.25씩 주는 건 어떨까요? 1로 되어있으니 두줄로 되어있을 때 너무 촘촘해 보이는 감이 있는 것 같아요. 

* line-height 1.0
<img width="274" alt="스크린샷 2021-08-09 오전 11 38 45" src="https://user-images.githubusercontent.com/67677561/128655292-5b9a315e-ba54-405e-ab49-cbb7063f126d.png">

* line-height 1.25
<img width="278" alt="스크린샷 2021-08-09 오전 11 38 33" src="https://user-images.githubusercontent.com/67677561/128655290-c11c1272-6144-4399-b9dd-61e1a91e641c.png">

2021-08-09 02:41 UTC, sunhpark42 commented on frontend/src/pages/DrinksDetailPage/styles.ts
> +  padding: 2rem 0;
그리고 전 이부분이 좀 넓어서,
선호도 section padding을 1로 줄이고, 상세정보 섹션 margin bottomd을 3rem, 리뷰헤딩과 리뷰 권유 카드(?) 사이의 간격을 0.3rem정도 주면 좋을 것 같아요,.
<img width="391" alt="스크린샷 2021-08-09 오전 11 37 55" src="https://user-images.githubusercontent.com/67677561/128655217-53181423-3bb5-4c62-8348-018820d5c0ed.png">

2021-08-09 02:41 UTC, sunhpark42 commented on frontend/src/pages/DrinksDetailPage/styles.ts
> +const PreferenceSection = styled.section<{ isScrolled: boolean }>`
![ezgif com-gif-maker (7)](https://user-images.githubusercontent.com/67677561/128654905-16d34395-b12d-4534-9262-81971080cad0.gif)
이런느낌!

2021-08-10 08:06 UTC, devhyun637 commented on frontend/src/components/Review/DisableWriteReview.tsx
> +const DisableWriteReview = ({ onClick }: { onClick: MouseEventHandler<HTMLButtonElement> }) => {
Props로 긴 이름을 drilling 하다보니깐 마지막에는 괜찮겠지 라는 생각으로한건데, 카드 전체가 그 onClick을 한다는 오해의 여지가 있군요
수정하였습니다! https://github.com/woowacourse-teams/2021-jujeol-jujeol/pull/290/commits/fd947fce783f57c57826156a28200c94a3bd45d7

2021-08-10 08:25 UTC, devhyun637 commented on frontend/src/pages/DrinksDetailPage/index.tsx
> +  };
이거 시간이 아닌 상태관리는 어떻게 해주어야할까요?
누르는 시점에만 true이면 되고, 그 나머지에서는 false가 되어야하는데 시간 말고 setState(false)를 어느 시점에 주어야할까여

2021-08-10 08:31 UTC, sunhpark42 commented on frontend/src/pages/DrinksDetailPage/index.tsx
> +  };
preferenceRef.current?.scrollIntoView({ behavior: 'smooth' }); 가 preferenceRef의 element가 보여 질 때까지 scroll을 하는 거라고 이해했는데 맞나용? 맞다면 해당 엘리먼트가 화면에 들어왔는지를 기준으로 잡는건 어떨까요?

2021-08-10 11:02 UTC, devhyun637 commented on frontend/src/components/Review/NoReviews.styles.ts
> +    span {
word-break 를 line-break로 수정하였습니다!

2021-08-10 12:33 UTC, devhyun637 commented on frontend/src/hooks/useReviews.ts
> +  useInfinityScroll({ target: observerTargetRef, fetchNextPage, hasNextPage });
좋습니다! 의존성을 분리하느 거 좋습니다. https://github.com/woowacourse-teams/2021-jujeol-jujeol/pull/290/commits/03d05091c0277c4f2d0f1738526552e88cb080dc

2021-08-11 03:23 UTC, devhyun637 commented
서니!
전체적으로 코드 리뷰 같이했지만 한번 더 봐주세용!,!

1. 리뷰 API 변경에 따른 코드 리팩토링
2. 변화가 있는 `preference` 부분에 대해서만 상태로 관리
3. 상세페이지 전체적인 여백 수정 및 각 글자에 line-height 1.25 부여

다음으로 미뤄진 기능들 (생각해볼것들)
1. 어떻게 하면 선호도를 입력하게 하는 로직을 자연스러운 애니메이션으로 구사할 수 있을지 (현재 어느 시점에 isBlinked 상태를 false로 만들지, 또는 focus로 사용했을 때 blur를 해야할 지 명확하지 않음) --> 내일중 으로 삽질한 내용 정리해볼게요!
2. 전체적인 글자를 컴포넌트로 관리를 해야할 듯 (각 글자마다 line-height가 업거나/ 1.25/ 1.5 등으로 통일성이 없음)

2021-08-11 04:38 UTC, sunhpark42 approved these changes
여러저러 많은 기능 구현하느라 고생하셨습니다! 
코드는 같이 본 부분이랑, 따로 이해한가는 부분 다 봤고, 몇몇 리팩토링은 지금 당장 해결 못할 것 같아서, 기능 정상동작하므로 어프로브 하겠습니다~ 고생하셨어요!

2021-08-11 04:38 UTC, sunhpark42 commented on frontend/src/pages/DrinksDetailPage/index.tsx
> +            value={currentPreferenceRate}
굿굿

2021-08-11 05:04 UTC, merged