feat: 검색 및 검색페이지 테스트
woowacourse-teams/2021-jujeol-jujeol pull request #417
Opened 2021-10-12 04:25 UTC by devhyun637

## resolve #273

### 설명
검색페이지 테스트코드 작성중입니다..! 완료가 되면 리뷰요청하겠습니다. 
아마 마크업과 충돌이 많이 날 것 같은데, 마크업 같이 작업한거 올리면 제가 충돌 해결하고, 그때 코드리뷰 해주시면 될 것 같습니당

- [x] 검색 페이지 테스트코드 작성
- [x] 검색결과 페이지 테스트코드 작성

2021-10-25 17:38 UTC, devhyun637 commented on frontend/src/components/SearchBar/SearchBar.tsx
> +    if (value === '') return;
당연히 input에 `required` 속성때문에 안될건 알지만, 최대한 방어적인 코드를 짤 수 있게 테스트가 도와주더라구요. 테스트짱

2021-10-25 17:49 UTC, devhyun637 commented on frontend/src/pages/SearchPage/test.tsx
> +        />
Route는 페이지를 의미하고, Switch는 children에 있는 Route를 path가 일치하는 페이지를 위에서부터 순서대로 매칭해준다. 따라서 Switch문 밖에 Route가 있을 수 있다!

MemoryRouter는 브라우저에서 사용하는 URL 말고 메모리에 데이터를 저장해서 브라우저가 아닌 환경 (테스트, 리액트 네이티브)에서 사용하기 좋다. (하지만 browserRouter 처럼 뒤로가기 기능을 사용할 수 없다)

제가 이해한 것이 맞을까요? 머릿속으로는 서니가 설명해준게 이해가 되었는데, 말로 또 하려니깐 어렵네용👀밑에 있는 [Route에 location을 mapping해주는 방식](https://reactrouter.com/web/guides/testing/checking-location-in-tests) 덕분에 쉽게 location에 대한 테스트를 할 수 있었습니다!! 커스텀 렌더러 짱

2021-10-25 17:50 UTC, devhyun637 commented on frontend/src/pages/SearchResultPage/NoSearchResults.tsx
> +        <CardList count={7} colGap="1rem" title="검색 결과가 없을 때 술 추천 리스트">
title이 장황한데 한번 봐주세용!,!

2021-10-25 17:53 UTC, devhyun637 commented on frontend/src/pages/SearchResultPage/test.tsx
> +    await waitFor(() => expect(API.getSearchResults).toBeCalled());
[waitFor](https://testing-library.com/docs/dom-testing-library/api-async/#waitfor)은 비동기와 같이 기다려야하는 것이 필요한 동작에서 쓰이는 메서드..!!

2021-10-25 18:04 UTC, devhyun637 commented on frontend/src/apis/requests.ts
> +    throw data;
후후.. 별의별짓 다해봤는데, 이렇게 하면 되더라구요..? 
현재 data는 unknown type 입니다. typeScript가 업데이트가 되면서 [타입의 안전성](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#defaulting-to-the-unknown-type-in-catch-variables---useunknownincatchvariables)때문에 catch 의 error 타입의 default 값이 any에서 unknown으로 변경되었다고 합니다. 왜 맘대로 바꿔ㅠㅠㅠ

해결하는 방법은 현재 공식문서에 나와있는 것처럼
1. `catch(error:any)`로 변경한다.
2. 타입스크립트 설정에 `useUnknownInCatchVariables:false`를 추가한다.
3. `if (error instanceof Error)`로 분기처리해서 사용한다.
이렇게인 것 같은데 axios를 사용하고 있지만, AxiosError 타입을 instanceof로 비교가 불가능해서(왜인지 모르겠음) 현재는 가장 코드를 적게 건들이는 구조분해할당의 방식을 사용하여 해결하였습니다..ㅎㅎ 


(1) 뭔가 request에서 에러인 것을 분기처리하는 것, 아니면 (2) 어차피 사용자에게 보여지는 최상단에서 에러 핸들링을 하는 게 가장 맞지 않을까라는 생각에 리액트 쿼리의 onError에서 처리를 해주는 것, (3) axios의 인터셉터에서 하나의 객체를 만들어버리는 것에서 가장 에러핸들링을 하는 역할이 적합한건 개인적으로 (2)라고 생각하는데 어느 에러냐에 따라서는 (1), (3)도 나쁘지않은 것 같구 어렵습니다 👀

2021-10-25 18:06 UTC, devhyun637 commented
서니~ 드디어 숙원사업인 모든 페이지 테스트코드가 .. 따흑..

이번에는 배운 것들이 많아서 다음에 또 질문하지 않기 위해서 한번 정리할 겸 어떤 방식으로 테스트코드를 작성했는지 코멘트를 달았습니다. 잘못된 것들이 있다면 알려주세용 !! 또 에러핸들링은 지금 당장은 저렇게 구조분해로 해결하고, 11월에 좀 더 견고하게 해보는 방식을 고민해봐도 좋을 것 같습니다!!

2021-10-26 01:22 UTC, sunhpark42 commented on frontend/src/components/SearchBar/SearchBar.tsx
> +    if (value === '') return;
한 번 더 validation하는거 좋아용

2021-10-26 01:22 UTC, sunhpark42 commented on frontend/src/pages/SearchPage/test.tsx
> +        />
정리왕 티케

2021-10-26 01:23 UTC, sunhpark42 commented on frontend/src/pages/SearchResultPage/NoSearchResults.tsx
> +        <CardList count={7} colGap="1rem" title="검색 결과가 없을 때 술 추천 리스트">
여기 타이틀은 그냥 술 추천 리스트면 될 것 같아요! 검색결과가 없을때만 나오는건 맞지만, 이미 위에서 검색결과 없음이 표시된 이후라, 검색결과가 없다는 내용은 없어도 될 것 같습니당

2021-10-26 01:41 UTC, sunhpark42 commented on frontend/src/apis/requests.ts
> +    throw data;
오 타입스크립트가 바꿔버려서 Error 타입을 아무리 넣어도 계속 에러가 났던 거군요! ㅎㅎ 알아봐 주셔서 감사해용. ㅋㅋㅋ 공식문서에 나와있는 1,2,3 다 이게 뭐람싶네요..any 쓰지 말라며... 3번처럼 사용하는게 가장 타당한 것 같아서 이렇게 작성해 봤는데, 어떻게 생각하시나용??
![image](https://user-images.githubusercontent.com/67677561/138794184-26f5bf10-9895-4ece-810e-eac49c7f4e62.png)

에러핸들리링 부분은 리액트 쿼리를 사용하고 있어서, onError에서 에러를 처리하는것이 에러핸들링에는 가장 적합하다고 생각합니다. 굳이굳이 나누자면 request에서 network에러나 500에러 정도만 다르게 던지는 것 정도..? 근데 현재 사용/발생하고 있는 에러에서는 당장 필요하지 않은 것 같아 이부분은 시간을 충분히 두고 고민해보는게 더 좋겠습니당

2021-10-26 01:43 UTC, sunhpark42 requested changes
안녕하세요 티케! 이것저것 다 시도해보고 이유도 섦명해 주셔서 감사해용!
title 에 관한 것과, error 타입에 대해서 코멘트 남긴게 있어서 확인 부탁드립니다!

어제 피곤했을텐데 진짜..넘 멋져여.. 어케 다했대..👍👍

2021-10-26 03:47 UTC, devhyun637 commented on frontend/src/apis/requests.ts
> +    throw data;
제안한방법으로 타입가드 써서 수정했습니다~!

2021-10-26 05:26 UTC, sunhpark42 approved these changes
굿굿!

2021-10-26 05:29 UTC, merged