feat: 데스크탑 웹으로 서비스 접속 시 화면에 배경을 추가한다.
woowacourse-teams/2021-jujeol-jujeol pull request #454
Opened 2021-10-26 09:26 UTC by sunhpark42

## resolve #453

### 설명
* netlify를 이용하여 선 배포 해보았습니다. (https://loving-darwin-bc4471.netlify.app/)

![스크린샷 2021-10-26 오후 4 46 28](https://user-images.githubusercontent.com/67677561/138849925-f5d76152-aa3b-4316-bcb3-a5f8bd61208c.png)

https://user-images.githubusercontent.com/67677561/138849948-fcf7e19f-00bb-40f6-87e6-8a3b67d52eb1.mov

* 아직 글을 뭐로 적는게 좋을지 모르겠어서 더 좋은 멘트가 떠오른다면 말씀 부탁드려요!
* 검색엔진에서 검색 시 페이지 컨텐츠가 조금이라도 보였으면 하는 마음으로 index.html에 바로 elements를 작성했습니다.
* 별도 추상화는 진행하지 않았고, 스타일 적용 역시 js 가 로드 되기전 바로 css를 이용해서 적용 되도록 했습니다!

2021-10-26 23:56 UTC, devhyun637 requested changes
우리 앱 너무 짱예쁘다!!!!!!!!!!!!!!!!!!!!! 너무 좋네요!
몇가지 성능적인 측면이랑 주석삭제 안된 부분 코멘트 달았는데, 확인부탁해용!

서니가 최고의 복지다..👍👍👍
예쁜 디자인 감사합니다.

2021-10-26 23:56 UTC, devhyun637 commented on frontend/src/GlobalStyle.tsx
> +        /* background-color: ${COLOR.GRAY_100}; */
이부분 삭제해주세용!

2021-10-26 23:56 UTC, devhyun637 commented on frontend/public/index.html
> +  <link rel="stylesheet" href="./index.css" />
```suggestion
  <link rel="preload" href="./index.css" as="style" />
```

성능향상을 위해서 이렇게 쓰는 것도 가능하대용 👍

2021-10-26 23:56 UTC, devhyun637 commented on frontend/public/index.css
> +}
<img width="80%" alt="스크린샷 2021-10-27 오전 8 53 35" src="https://user-images.githubusercontent.com/59258239/138977231-d8da526c-9f03-46f2-a090-9e110df478fd.png">

이부분 max-width를 조금 더 늘려도 되지 않을까 싶은 생각인데 어떠하신가용??

2021-10-27 00:05 UTC, devhyun637 commented on frontend/public/index.css
> +}
흠.. 아니다 저정도 일때 아무것도 없으면 휑하겠다. 그대로 가죠

2021-10-27 00:20 UTC, sunhpark42 commented on frontend/src/GlobalStyle.tsx
> +        /* background-color: ${COLOR.GRAY_100}; */
아 여기 삭제했는데 왜있지?? 했는데 push 를 안했네요. 죄송함다..

2021-10-27 00:21 UTC, sunhpark42 commented on frontend/public/index.html
> +  <link rel="stylesheet" href="./index.css" />
오오.. 넘 좋아요

2021-10-27 00:22 UTC, sunhpark42 commented on frontend/public/index.css
> +}
그럼 좀 더 늘리는 대신, 저때는 말풍선 크기를 조금 줄여볼게용!

2021-10-27 00:58 UTC, sunhpark42 commented on frontend/public/index.html
> +  <link rel="stylesheet" href="./index.css" />
사용할 때 preload는 미리 파일을 load하는거지, 적용하는 건 아니라서, 해당 구문을 변경하지 않고, 티케가 제안해주신 내용을 위에 추가했습니다~~

2021-10-27 01:25 UTC, devhyun637 approved these changes
굳굳 확인했습니다~

2021-10-27 01:26 UTC, merged