fix: 프론트엔드 빌드 오류 수정
woowacourse-teams/2021-jujeol-jujeol pull request #631
Opened 2022-01-08 10:07 UTC by soulgchoi

## resolve #630 

### 설명
- 문제 원인은 `tar -xvf` 명령어에서 타겟 폴더를 입력하지 않았기 때문인 것으로 보입니다.
- 타겟 폴더가 설정되어 있지 않아 원하는 위치에 압축해제가 되지 않기 때문에 옮길 빌드 파일을 찾지 못하는 문제를 해결했습니다.
- 압축해제와 파일 삭제 및 옮기는 절차를 분리했습니다.

2022-01-09 06:31 UTC, sunhpark42 requested changes
nginx 마운트 이슈가 있어서 해당내용 확인 부탁드립니다~

2022-01-09 06:31 UTC, sunhpark42 commented on .github/workflows/front-prod-deploy.yml
> +            rm -rf /home/ubuntu/jujeol-jujeol/frontend/deploy &&
안녕하세요 소롱~ 이 부분 다음과 같이 수정이 필요할 것 같아요.

```suggestion
            rm -rf /home/ubuntu/jujeol-jujeol/frontend/deploy/* &&
```

현재 nginx를 도커로 실행시키고 있는데, 폴더자체를 삭제해버리면 폴더의 주소값이 달라서 마운트가 해제되어

운영환경에서 프론트엔드 빌드 코드를 찾지 못하는 문제가 발생하네요!

2022-01-09 06:44 UTC, soulgchoi commented on .github/workflows/front-prod-deploy.yml
> +            rm -rf /home/ubuntu/jujeol-jujeol/frontend/deploy &&
아하 몰랐네요 수정할게요!

2022-01-19 12:20 UTC, sunhpark42 approved these changes

2022-01-19 12:31 UTC, merged